name = "pixelpaint"
main = "index.js"
compatibility_date = "2025-11-06"

[[kv_namespaces]]
binding = "PIXEL_STORE"
id = "f524cbbcfb5e4ac5bc17025efb0c8cd3"

[[kv_namespaces]]
binding = "USER_LOG"
id = "9d69f7211e0d4de294571fc1399e3854"
