name = "rplace-worker"
main = "index.js"
compatibility_date = "2025-11-06"

[[kv_namespaces]]
binding = "PIXEL_STORE"
id = "<deine-kv-id>"

[[kv_namespaces]]
binding = "USER_LOG"
id = "<deine-kv-id>"
