name = "rplace-worker"
main = "index.js"
compatibility_date = "2025-11-06"

[[kv_namespaces]]
binding = "PIXEL_STORE"
id = "54406a15f18d4d7ba466c50e28d14ed4"

[[kv_namespaces]]
binding = "USER_LOG"
id = "<deine-kv-id>"
